+JobFlavour = "espresso"

executable  = /afs/hep.wisc.edu/user/kaho/CMSSW_10_2_16_UL/src/flashggFinalFit/Background/bkgPlots-Data/sub0.sh
output  = /afs/hep.wisc.edu/user/kaho/CMSSW_10_2_16_UL/src/flashggFinalFit/Background/bkgPlots-Data/sub0.out
error  = /afs/hep.wisc.edu/user/kaho/CMSSW_10_2_16_UL/src/flashggFinalFit/Background/bkgPlots-Data/sub0.err
log  = /afs/hep.wisc.edu/user/kaho/CMSSW_10_2_16_UL/src/flashggFinalFit/Background/bkgPlots-Data/sub0.log

max_retries = 1
queue 1
