+JobFlavour = "espresso"

executable  = /afs/hep.wisc.edu/user/kaho/CMSSW_10_2_16_UL/src/flashggFinalFit/Background/bkgPlots-Data/sub1.sh
output  = /afs/hep.wisc.edu/user/kaho/CMSSW_10_2_16_UL/src/flashggFinalFit/Background/bkgPlots-Data/sub1.out
error  = /afs/hep.wisc.edu/user/kaho/CMSSW_10_2_16_UL/src/flashggFinalFit/Background/bkgPlots-Data/sub1.err
log  = /afs/hep.wisc.edu/user/kaho/CMSSW_10_2_16_UL/src/flashggFinalFit/Background/bkgPlots-Data/sub1.log

max_retries = 1
queue 1
