+JobFlavour = "espresso"

executable  = /afs/hep.wisc.edu/user/kaho/CMSSW_10_2_16_UL/src/flashggFinalFit/Background/bkgPlots-Data/sub3.sh
output  = /afs/hep.wisc.edu/user/kaho/CMSSW_10_2_16_UL/src/flashggFinalFit/Background/bkgPlots-Data/sub3.out
error  = /afs/hep.wisc.edu/user/kaho/CMSSW_10_2_16_UL/src/flashggFinalFit/Background/bkgPlots-Data/sub3.err
log  = /afs/hep.wisc.edu/user/kaho/CMSSW_10_2_16_UL/src/flashggFinalFit/Background/bkgPlots-Data/sub3.log

max_retries = 1
queue 1
